name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build WAR file
      run: mvn clean install

    - name: Deploy to Tomcat
      uses: peaceiris/actions-tomcat@v2
      with:
        tomcat_version: '9.0.45'
        tomcat_url: 'http://54.197.74.82:8080'
        manager_script_username: ${{ secrets.TOMCAT_USERNAME }}
        manager_script_password: ${{ secrets.TOMCAT_PASSWORD }}
        war: 'target/rajesh.war'
